(function() {
  var bindings = YUI.framework.QCBindings;
    bindings.add ("blackberry.utils should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447640");
    bindings.add ("blackberry.utils.generateUniqueId should exist and is a function", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447641");
    bindings.add ("blackberry.utils.parseURL should exist and is a function", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447642");
    bindings.add ("For a blackberry.utils.URL object, getURLParameter should exist and is a function", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447643");
    bindings.add ("For a blackberry.utils.URL object, getURLParameterByIndex should exist and is a function", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447644");
    bindings.add ("For a blackberry.utils.URL object, property host should exist and be readOnly", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447645");
    bindings.add ("For a blackberry.utils.URL object, property port should exist and be type of Number and readOnly", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447646");
    bindings.add ("blackberry.utils.parseURL - http explicitly define port should work", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447647");
    bindings.add ("blackberry.utils.parseURL - https explicitly define port should work", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447648");
    bindings.add ("blackberry.utils.parseURL - http implicitly define port should work", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447649");
    bindings.add ("blackberry.utils.parseURL - https implicitly define port should work", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447650");
    bindings.add ("blackberry.utils.parseURL - local protocal should work on getURLParameterByIndex", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447651");
    bindings.add ("blackberry.utils.parseURL - local protocal should work on getURLParameter", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2447652");
    bindings.add ("blackberry.utils.blobToString should exist and is a function", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version  + "\\US2314 - blackberry.utils", "2470900");
    bindings.add ("blackberry.utils.stringToBlob should exist and is a function", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_" + YUI.framework.bundle_version  + "\\US2314 - blackberry.utils", "2470848");
    bindings.add ("blackberry.utils.stringToBlob and BlobToString should work", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\PlayBook JS Extensions_"  + YUI.framework.bundle_version + "\\US2314 - blackberry.utils", "2470847");
})();
