(function() {
  var bindings = YUI.framework.QCBindings;
    bindings.add ("blackberry.ui.dialog should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417525");
    bindings.add ("blackberry.ui.dialog.D_OK should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417526");
    bindings.add ("blackberry.ui.dialog.D_SAVE should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417527");
    bindings.add ("blackberry.ui.dialog.D_DELETE should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417528");
    bindings.add ("blackberry.ui.dialog.D_YES_NO should exist should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417529");
    bindings.add ("blackberry.ui.dialog.D_OK_CANCEL should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417557");
    bindings.add ("blackberry.ui.dialog.C_CANCEL should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417558");
    bindings.add ("blackberry.ui.dialog.C_OK should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417559");
    bindings.add ("blackberry.ui.dialog.C_SAVE should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417560");
    bindings.add ("blackberry.ui.dialog.C_DISCARD should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417561");
    bindings.add ("blackberry.ui.dialog.C_DELETE should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417562");
    bindings.add ("blackberry.ui.dialog.C_YES should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417563");
    bindings.add ("blackberry.ui.dialog.C_NO should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417564");
    bindings.add ("blackberry.ui.dialog.C_NO should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417565");
    bindings.add ("blackberry.ui.dialog.C_NO should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417566");
    bindings.add ("standardAsk D_OK_noOptions should pop up message OK button only", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417567");
    bindings.add ("standardAsk Save dialog (Save, Disgard, Cancel) should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417568");
    bindings.add ("standardAsk Save dialog with default choice C_DISCARD should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417569");
    bindings.add ("standardAsk DELETE dialog (Delete, Cancel) should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417570");
    bindings.add ("standardAsk DELETE dialog with default choice C_DELETE should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417573");
    bindings.add ("standardAsk YES_NO dialog (YES, NO) should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417574");
    bindings.add ("standardAsk YES_NO dialog with default choise NO should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417575");
    bindings.add ("standardAsk OK_CANCEL dialog (OK, CANCEL) should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417576");
    bindings.add ("standardAsk OK_CANCEL dialog with choise CANCEL should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417577");
    bindings.add ("customAsk_withoutOptions() should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417578");
    bindings.add ("customAsk_SecondOption() should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417579");
    bindings.add ("undefinded - Timeout afer pops up dialog should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417580");
    bindings.add ("undefinded - pops up dialog with setting to background apps should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417581");
    bindings.add ("undefinded - background apps only should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.ui.dialog", "2417582");
})();
