(function() {
  var bindings = YUI.framework.QCBindings;
    bindings.add ("blackberry.system.ALLOW should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417583");
    bindings.add ("blackberry.system.DENY should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417584");
    bindings.add ("blackberry.system.PROMPT should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417585");
    bindings.add ("blackberry.system.hasCapability should be a function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417586");
    bindings.add ("blackberry.system.hasCapability input.keyboard.issuretype should return boolean", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417587");
    bindings.add ("blackberry.system.hasDataCoverage should be a function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417588");
    bindings.add ("blackberry.system.hasPermission should be a function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417589");
    bindings.add ("blackberry.system.isMassStorageActive should be a function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417590");
    bindings.add ("blackberry.system.setHomeScreenBackground should be a function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417591");
    bindings.add ("blackberry.system.model should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417592");
    bindings.add ("blackberry.system.scriptApiVersion should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417593");
    bindings.add ("blackberry.system.softwareVersion should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417594");
    bindings.add ("blackberry.system.setHomeScreenBackground should work when images are from SDCard/store", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417595");
    bindings.add ("blackberry.system.model should return device mode", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417596");
    bindings.add ("blackberry.system.hasCapability all return values should be boolean", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417597");
    bindings.add ("blackberry.system.event namespace should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417598");
    bindings.add ("blackberry.system.event.KEY_BACK should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417599");
    bindings.add ("blackberry.system.event.KEY_CONVENIENCE_1 should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417600");
    bindings.add ("blackberry.system.event.KEY_CONVENIENCE_2 should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417601");
    bindings.add ("blackberry.system.event.KEY_STARTCALL should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417602");
    bindings.add ("blackberry.system.event.KEY_ENDCALL should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417603");
    bindings.add ("blackberry.system.event.KEY_VOLUMEDOWN should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417604");
    bindings.add ("blackberry.system.event.KEY_VOLUMEUP should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417605");
    bindings.add ("blackberry.system.onCoverageChange should be a function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417606");
    bindings.add ("blackberry.system.onHardwareKey should be a function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417607");
    bindings.add ("blackberry.system.handle_KEY_BACK should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417608");
    bindings.add ("blackberry.system.KEY_BACK unregistry should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417609");
    bindings.add ("blackberry.system.handle_KEY_MENU should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417610");
    bindings.add ("blackberry.system.KEY_MENU unregistry should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417611");
    bindings.add ("blackberry.system.handle_KEY_CONVENIENCE_1 should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417612");
    bindings.add ("blackberry.system.KEY_CONVENIENCE_1 unregistry should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417613");
    bindings.add ("blackberry.system.handle_KEY_CONVENIENCE_2 should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417614");
    bindings.add ("blackberry.system.KEY_CONVENIENCE_2 unregistry should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417615");
    bindings.add ("blackberry.system.handle_KEY_STARTCALL should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417616");
    bindings.add ("blackberry.system.KEY_STARTCALL unregistry should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417617");
    bindings.add ("blackberry.system.handle_KEY_ENDCALL should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417618");
    bindings.add ("blackberry.system.KEY_ENDCALL unregistry should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417619");
    bindings.add ("blackberry.system.handle_KEY_VOLUMEDOWN should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417620");
    bindings.add ("blackberry.system.KEY_VOLUMEDOWN unregistry should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417621");
    bindings.add ("blackberry.system.handle_KEY_VOLUMEUP should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417622");
    bindings.add ("blackberry.system.KEY_VOLUMEUP unregistry should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417623");
    bindings.add ("blackberry.system.onCoverageChange() should work", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\blackberry.system", "2417624");
})();
