(function() {
  var bindings = YUI.framework.QCBindings;
    bindings.add ("blackberry.app should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436046");
    bindings.add ("blackberry.app.event should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436047");
    bindings.add ("blackberry.app.author should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436048");
    bindings.add ("blackberry.app.authorEmail should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436049");
    bindings.add ("blackberry.app.authorURL should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436050");
    bindings.add ("blackberry.app.copyright should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436051");
    bindings.add ("blackberry.app.description should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436052");
    bindings.add ("blackberry.app.id should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436053");
    bindings.add ("blackberry.app.license should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436054");
    bindings.add ("blackberry.app.licenseURL should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436055");
    bindings.add ("blackberry.app.name should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436056");
    bindings.add ("blackberry.app.version should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436057");
    bindings.add ("blackberry.app.exit should exist and be type of function", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436058");
    bindings.add ("blackberry.app properties should be readonly", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436059");
    bindings.add ("Manual Test - should show all the application properties", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436060");
    bindings.add ("Manual Test - blackberry.app.event onBackground event should trigger when application is set to background", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436061");
    bindings.add ("Manual Test - blackberry.app.event onForeground event should trigger when application is set to foreground", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2087 - blackberry.app", "2436062");
})();