(function() {
	var bindings = YUI.framework.QCBindings;
	bindings.add("blackberry.ui.dialog.standardAsk should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430490");
	bindings.add("blackberry.ui.dialog.customAsk should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430491");
	bindings.add("blackberry.ui.dialog.standardAsk should be a function", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430492");
	bindings.add("blackberry.ui.dialog.customAsk should be a function", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430493");
	bindings.add("blackberry.ui.dialog.D_OK should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430494");
	bindings.add("blackberry.ui.dialog.D_SAVE should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430495");
	bindings.add("blackberry.ui.dialog.D_DELETE should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430496");
	bindings.add("blackberry.ui.dialog.D_YES_NO should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430497");
	bindings.add("blackberry.ui.dialog.D_OK_CANCEL should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430498");
	bindings.add("blackberry.ui.dialog.LOC_BOTTOM should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430499");
	bindings.add("blackberry.ui.dialog.LOC_CENTER should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430500");
	bindings.add("blackberry.ui.dialog.LOC_TOP should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430501");
	bindings.add("blackberry.ui.dialog.SIZE_FULL should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430502");
	bindings.add("blackberry.ui.dialog.SIZE_LARGE should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430503");
	bindings.add("blackberry.ui.dialog.SIZE_MEDIUM should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430504");
	bindings.add("blackberry.ui.dialog.SIZE_SMALL should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430505");
	bindings.add("blackberry.ui.dialog.SIZE_TALL should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430506");
	bindings.add("standardAsk D_OK_noOptions should pop up message OK button only", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430507");
	bindings.add("standardAsk Save dialog (Save, Disgard, Cancel) should work", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430508");
	bindings.add("standardAsk DELETE dialog (Delete, Cancel) should work", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430509");
	bindings.add("standardAsk YES_NO dialog (YES, NO) should work", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430510");
	bindings.add("standardAsk OK_CANCEL dialog (OK, CANCEL) should work", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430511");
	bindings.add("blackberry.ui.dialog.standardAsk should appear at the bottom", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430512");
	bindings.add("blackberry.ui.dialog.standardAsk should appear at the top", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430513");
	bindings.add("blackberry.ui.dialog.standardAsk should appear in the middle", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430514");
	bindings.add("blackberry.ui.dialog.standardAsk should appear full sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430515");
	bindings.add("blackberry.ui.dialog.standardAsk should appear large sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430516");
	bindings.add("blackberry.ui.dialog.standardAsk should appear medium sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430517");
	bindings.add("blackberry.ui.dialog.standardAsk should appear small sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430518");
	bindings.add("blackberry.ui.dialog.standardAsk should appear tall sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430519");
	bindings.add("blackberry.ui.dialog.customAsk should appear at the bottom", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430520");
	bindings.add("blackberry.ui.dialog.customAsk should appear at the top", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430521");
	bindings.add("blackberry.ui.dialog.customAsk should appear in the middle", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430522");
	bindings.add("blackberry.ui.dialog.customAsk should appear full sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430523");
	bindings.add("blackberry.ui.dialog.customAsk should appear large sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430524");
	bindings.add("blackberry.ui.dialog.customAsk should appear medium sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430525");
	bindings.add("blackberry.ui.dialog.customAsk should appear small sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430526");
	bindings.add("blackberry.ui.dialog.customAsk should appear tall sized", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2296 - blackberry.ui.dialog", "2430527");
})();