(function() {
var bindings = YUI.framework.QCBindings;
bindings.add ("blackberry.invoke should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428950");
bindings.add ("blackberry.invoke.APP_ADDRESSBOOK should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428951");
bindings.add ("blackberry.invoke.APP_BLUETOOTH_CONFIG should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428952");
bindings.add ("blackberry.invoke.APP_CALCULATOR should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428953");
bindings.add ("blackberry.invoke.APP_CALENDAR should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428954");
bindings.add ("blackberry.invoke.APP_CAMERA should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428955");
bindings.add ("blackberry.invoke.APP_MAPS should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428956");
bindings.add ("blackberry.invoke.APP_MEMOPAD should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428957");
bindings.add ("blackberry.invoke.APP_MESSAGES should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428958");
bindings.add ("blackberry.invoke.APP_PHONE should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428959");
bindings.add ("blackberry.invoke.APP_SEARCH should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428960");
bindings.add ("blackberry.invoke.APP_TASKS should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428961");
bindings.add ("blackberry.invoke.APP_BROWSER should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428962");
bindings.add ("blackberry.invoke.APP_JAVA should exist","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428963");
bindings.add ("blackberry.invoke.APP_ADDRESSBOOK should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428964");
bindings.add ("blackberry.invoke.APP_BROWSER should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428965");
bindings.add ("blackberry.invoke.APP_CALENDAR should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428966");
bindings.add ("blackberry.invoke.APP_CAMERA should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428967");
bindings.add ("blackberry.invoke.APP_JAVA should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428968");
bindings.add ("blackberry.invoke.APP_MAPS should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428969");
bindings.add ("blackberry.invoke.APP_MEMO should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428970");
bindings.add ("blackberry.invoke.APP_MESSAGE should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428971");
bindings.add ("blackberry.invoke.APP_PHONE should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428972");
bindings.add ("blackberry.invoke.APP_SEARCH should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428973");
bindings.add ("blackberry.invoke.APP_TASK should return invalid type when passed undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428974");
bindings.add ("blackberry.invoke.APP_JAVA should return undefined","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428975");
bindings.add ("blackberry.invoke.APP_JAVA should return undefined when passed a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428976");
bindings.add ("Manual Test 1 should invoke addressbook","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428977");
bindings.add ("Manual Test 2 should invoke Bluetooth Config","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428978");
bindings.add ("Manual Test 3 should invoke Calculator","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428979");
bindings.add ("Manual Test 4 should invoke Calendar","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428980");
bindings.add ("Manual Test 5 should invoke Maps","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428981");
bindings.add ("Manual Test 6 should invoke Memopad","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428982");
bindings.add ("Manual Test 7 should invoke Messages","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428983");
bindings.add ("Manual Test 8 should invoke Phone","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428984");
bindings.add ("Manual Test 9 should invoke Search","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428985");
bindings.add ("Manual Test 10 should invoke Tasks","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428986");
bindings.add ("Manual Test 11 should invoke Browser","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428987");
bindings.add ("Manual Test 1 should invoke Address Book when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428988");
bindings.add ("Manual Test 2 should invoke Browser when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428989");
bindings.add ("Manual Test 3 should invoke Calendar when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428990");
bindings.add ("Manual Test 4 should invoke Camera when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428991");
bindings.add ("Manual Test 5 should invoke Maps when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428992");
bindings.add ("Manual Test 6 should invoke Memo when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428993");
bindings.add ("Manual Test 7 should invoke Message when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428994");
bindings.add ("Manual Test 8 should invoke Phone when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428995");
bindings.add ("Manual Test 9 should invoke Search when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428996");
bindings.add ("Manual Test 10 should invoke Tasks when parameter is a null","BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2144 - blackberry.invoke","2428997");
})();