(function() {
	var bindings = YUI.framework.QCBindings;
	bindings.add("blackberry.system namespace should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430468");
	bindings.add("blackberry.system.ALLOW should exist and return 0", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430469");
	bindings.add("blackberry.system.DENY should exist and return 1", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430470");
	bindings.add("blackberry.system.PROMPT should exist and return 2", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430471");
	bindings.add("blackberry.system.hasCapability() should return a boolean", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430472");
	bindings.add("blackberry.system.hasDataCoverage() should return a boolean", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430473");
	bindings.add("blackberry.system.hasPermission() should return ALLOW", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430474");
	bindings.add("blackberry.system.isMassStorageActive() should return a boolean", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430475");
	bindings.add("blackberry.system.setHomeScreenBackground() should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430476");
	bindings.add("blackberry.system.model should exist and be readonly", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430477");
	bindings.add("blackberry.system.scriptApiVersion should exist and be readonly", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430478");
	bindings.add("blackberry.system.softwareVersion should exist and be readonly", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430479");
	bindings.add("blackberry.system.event.KEY_BACK should exist and return 0", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430480");
	bindings.add("blackberry.system.event.KEY_MENU should exist and return 1", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430481");
	bindings.add("blackberry.system.event.KEY_CONVENIENCE_1 should exist and return 2", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430482");
	bindings.add("blackberry.system.event.KEY_CONVENIENCE_2 should exist and return 3", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430483");
	bindings.add("blackberry.system.event.KEY_STARTCALL should exist and return 4", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430484");
	bindings.add("blackberry.system.event.KEY_ENDCALL should exist and return 5", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430485");
	bindings.add("blackberry.system.event.KEY_VOLUMEDOWN should exist and return 8", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430486");
	bindings.add("blackberry.system.event.KEY_VOLUMEUP should exist and return 7", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430487");
	bindings.add("blackberry.system.event.onCoverageChange () should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430488");
	bindings.add("blackberry.system.event.onHardwareKey() should exist", "BlackBerry Developer Tools\\WebWorks API\\PlayBook JS Extensions\\US2290 - blackberry.system", "2430489");
})();