(function() {  
	var bindings = YUI.framework.QCBindings;
	bindings.add ("blackberry.invoke.CalendarArguments should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421489");
	bindings.add ("blackberry.invoke.CalendarArguments.VIEW_NEW should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421490");
	bindings.add ("blackberry.invoke.CalendarArguments.VIEW_VIEW should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421491");
	bindings.add ("blackberry.invoke.CalendarArguments.VIEW_AGENDA should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421492");
	bindings.add ("blackberry.invoke.CalendarArguments.VIEW_DAY should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421493");
	bindings.add ("blackberry.invoke.CalendarArguments.VIEW_DEFAULT should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421494");
	bindings.add ("blackberry.invoke.CalendarArguments.VIEW_MONTH should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421495");
	bindings.add ("blackberry.invoke.CalendarArguments.VIEW_WEEK should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421496");
	bindings.add ("MANUAL 1 should invoke Calendar with empty CalendarArguments", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421497");
	bindings.add ("MANUAL 2 should invoke Calendar with VIEW_NEW CalendarArguments", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421498");
	bindings.add ("MANUAL 3 should invoke Calendar with VIEW_VIEW CalendarArguments", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421499");
	bindings.add ("MANUAL 4 should invoke Calendar with VIEW_AGENDA CalendarArguments", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421500");
	bindings.add ("MANUAL 5 should invoke Calendar with VIEW_DAY CalendarArguments", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421501");
	bindings.add ("MANUAL 6 should invoke Calendar with VIEW_DEFAULT CalendarArguments", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421502");
	bindings.add ("MANUAL 7 should invoke Calendar with VIEW_MONTH CalendarArguments", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421503");
	bindings.add ("MANUAL 8 should invoke Calendar with VIEW_WEEK CalendarArguments", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421504");
	bindings.add ("MANUAL 9 should invoke Calendar with CalendarArguments with view=7", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421505");
	bindings.add ("MANUAL 10 should invoke Calendar with CalendarArguments with view=string", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421506");
	bindings.add ("MANUAL 11 should invoke Calendar with CalendarArguments with Date object", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421507");
	bindings.add ("MANUAL 12 should invoke Calendar with CalendarArguments with Appointment Object", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5150 - blackberry.invoke", "2421508");
})();

