(function() {
  var bindings = YUI.framework.QCBindings;
    bindings.add ("blackberry.push should exist", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451630");
    bindings.add ("blackberry.push.ACCEPT should exist and is Number", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451631");
    bindings.add ("blackberry.push.getHeaderField should exist and is function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451632");
    bindings.add ("blackberry.push.getRequestURI should exist and is function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451633");
    bindings.add ("blackberry.push.closePushListener should exist and is function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451634");
    bindings.add ("blackberry.push.openPushListener should exist and is function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451635");
    bindings.add ("blackberry.push.getSource should exist and is function", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451636");
    bindings.add ("MANUAL register to BIS server should work properly", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451637");
    bindings.add ("MANUAL blackberry.push.openPushlistener(isChannelEncrypted/payload/ACCEPT/DECLINE_) should work properly and readonly", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451638");
    bindings.add ("MANUAL Un-register to BIS server should work properly", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451639");
    bindings.add ("MANUAL blackberry.push.closePushlistener should work properly", "BlackBerry Developer Tools\\WebWorks API\\BlackBerry JS Extensions\\BlackBerry JS Extensions_" + YUI.framework.bundle_version + "\\US5153 - blackberry.push", "2451640");
})();
