(function() {
  var bindings = YUI.framework.QCBindings;
    bindings.add ("createDocument in DOMImplementation should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472204");
    bindings.add ("createDocumentType in DOMImplementation should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472205");
    bindings.add ("loadXmlDocument in parser should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472206");
    bindings.add ("loadXmlString in parser should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472207");
    bindings.add ("getElementsByTagName should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472208");
    bindings.add ("Should be able to access node by index on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472209");
    bindings.add ("length property should work on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472210");
    bindings.add ("nodeName and nodeType should work in documentElement", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472211");
    bindings.add ("should be able to loop through the element nodes on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472212");
    bindings.add ("childNodes firstChild and nextSibling should work on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472213");
    bindings.add ("should be able to change nodeValue in text node", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472214");
    bindings.add ("should be able to traverse attribute list on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472215");
    bindings.add ("should be able to traverse the node tree on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472216");
    bindings.add ("parentNode should work", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472217");
    bindings.add ("should be able to get first child", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472218");
    bindings.add ("should be able to access last child", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472219");
    bindings.add ("should be able to access next sibling", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472220");
    bindings.add ("should be able to access the previous sibling", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472221");
    bindings.add ("getAttribute should work on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472222");
    bindings.add ("getAttributeNode should work on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472223");
    bindings.add ("setAttribute should work on the xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472224");
    bindings.add ("xml attribute should be able to be changed by nodeValue", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472225");
    bindings.add ("should be able to remove an xml element node", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472226");
    bindings.add ("should be able to remove current xml node", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472227");
    bindings.add ("should be able to remove a xml text node", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472228");
    bindings.add ("should be able to remove an xml attribute node by name", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472229");
    bindings.add ("should be able to remove xml attributes by object", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472230");
    bindings.add ("should be able to replace a xml element node", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472231");
    bindings.add ("replaceData should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472232");
    bindings.add ("exception should be thrown if index is out of range in replaceData", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472233");
    bindings.add ("exception should be thrown if negative index is in replaceData", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472234");
    bindings.add ("exception should be thrown if negative length is in replaceData", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472235");
    bindings.add ("appendChild should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472236");
    bindings.add ("should be able to create and set a new xml attribute node", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472237");
    bindings.add ("should be able to create a xml attribute using setAttribute", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472238");
    bindings.add ("createTextNode should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472239");
    bindings.add ("createCDATASection should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472240");
    bindings.add ("createComment should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472241");
    bindings.add ("insertBefore should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472242");
    bindings.add ("insertData should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472243");
    bindings.add ("exception should be thrown if index is out of range in insertData", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472244");
    bindings.add ("exception should be thrown if negative index is in insertData", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472245");
    bindings.add ("cloneNode should work according to true condition on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472246");
    bindings.add ("cloneNode should work according to false condition on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472247");
    bindings.add ("XMLHttpRequest should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472248");
    bindings.add ("document nodeType should be 9 on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472249");
    bindings.add ("prefix should work properly on the xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472250");
    bindings.add ("localName should work properly on the xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472251");
    bindings.add ("namespaceURI should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472252");
    bindings.add ("baseURI should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472253");
    bindings.add ("ownerDocument should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472254");
    bindings.add ("textContent should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472255");
    bindings.add ("compareDocumentPosition should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472256");
    bindings.add ("hasChildNodes should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472257");
    bindings.add ("hasAttributes should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472258");
    bindings.add ("getElementsByTagNameNS should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472259");
    bindings.add ("isEqualNode should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472260");
    bindings.add ("isSameNode should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472261");
    bindings.add ("lookupNamespaceURI should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472262");
    bindings.add ("lookupPrefix should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472263");
    bindings.add ("should be able to traverse node list by item on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472264");
    bindings.add ("should be able to access attributes length on xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472265");
    bindings.add ("removeNamedItem should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472266");
    bindings.add ("data property should be supported on CDATA by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472267");
    bindings.add ("appendData should be supported on CDATA by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472268");
    bindings.add ("deleteData should be supported on CDATA by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472269");
    bindings.add ("insertData should be supported on CDATA by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472270");
    bindings.add ("CDATA insertData should throw exception if index is out of range", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472271");
    bindings.add ("replaceData should be supported on CDATA by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472272");
    bindings.add ("CDATA spliteText should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472273");
    bindings.add ("CDATA spliteData should throw exception when index is out of range", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472274");
    bindings.add ("CDATA substringData should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472275");
    bindings.add ("comment data proterty should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472276");
    bindings.add ("comment length property should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472277");
    bindings.add ("comment appendData should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472278");
    bindings.add ("comment deleteData should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472279");
    bindings.add ("comment insertData should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472280");
    bindings.add ("comment replaceData should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472281");
    bindings.add ("comment substringData should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472282");
    bindings.add ("setAttributeNS method should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472283");
    bindings.add ("hasAttributeNS method should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472284");
    bindings.add ("removeAttributeNS method should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472285");
    bindings.add ("getAttributeNodeNS method should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472286");
    bindings.add ("tagName property should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472287");
    bindings.add ("implementation property should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472288");
    bindings.add ("xmlEncoding property should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472289");
    bindings.add ("xmlStandalone should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472290");
    bindings.add ("doctype and its name should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472291");
    bindings.add ("ownerElement should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472292");
    bindings.add ("specified should be supported by xml dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\XML DOM tests", "2472293");
})();
