(function() {
  var bindings = YUI.framework.QCBindings;
    bindings.add ("document anchors len property should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472053");
    bindings.add ("document anchors innerHTML should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472054");
    bindings.add ("document forms length should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472055");
    bindings.add ("document forms name should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472057");
    bindings.add ("document images length should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472058");
    bindings.add ("document images id should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472059");
    bindings.add ("document links length property should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472060");
    bindings.add ("document links id should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472061");
    bindings.add ("document cookie should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472062");
    bindings.add ("document domain property should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472063");
    bindings.add ("document readyState should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472064");
    bindings.add ("document title property should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472065");
    bindings.add ("document url should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472067");
    bindings.add ("document getElementById should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472088");
    bindings.add ("document getElementsByName should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472101");
    bindings.add ("element className should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472102");
    bindings.add ("element dir set and get should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472103");
    bindings.add ("element disabled should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472104");
    bindings.add ("element id should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472105");
    bindings.add ("element innerHTML should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472106");
    bindings.add ("element lang should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472107");
    bindings.add ("element tabIndex should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472108");
    bindings.add ("element tagName should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472109");
    bindings.add ("element title should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472110");
    bindings.add ("anchor charset should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472111");
    bindings.add ("anchor href should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472112");
    bindings.add ("anchor hreflang should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472113");
    bindings.add ("anchor name should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472119");
    bindings.add ("anchor rel and rev should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472140");
    bindings.add ("anchor target should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472149");
    bindings.add ("anchor type should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472150");
    bindings.add ("area alt should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472151");
    bindings.add ("area coords should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472152");
    bindings.add ("area hash should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472153");
    bindings.add ("area host should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472154");
    bindings.add ("area hostname should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472155");
    bindings.add ("area pathname should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472156");
    bindings.add ("area protocol should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472157");
    bindings.add ("area search should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472158");
    bindings.add ("area shape should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472159");
    bindings.add ("area target should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472160");
    bindings.add ("base href should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472161");
    bindings.add ("base target should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472162");
    bindings.add ("body link alink and vlink should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472163");
    bindings.add ("body background should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472164");
    bindings.add ("body bgColor should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472165");
    bindings.add ("body text should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472166");
    bindings.add ("button form should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472167");
    bindings.add ("button name should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472168");
    bindings.add ("button type should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472169");
    bindings.add ("button value should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472170");
    bindings.add ("form elements should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472171");
    bindings.add ("form acceptCharset should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472172");
    bindings.add ("form length should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472173");
    bindings.add ("form action should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472174");
    bindings.add ("form target should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472175");
    bindings.add ("form name should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472176");
    bindings.add ("iframe align should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472177");
    bindings.add ("image align should be supported by html dom", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472178");
    bindings.add ("eval test should be passed at this html dom test", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472179");
    bindings.add ("boolean test should be passed at this html dom test", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML DOM tests", "2472180");
})();
