(function() {
  var bindings = YUI.framework.QCBindings;
    bindings.add ("webDatabase openDatabase should be recognized as defined", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468690");
    bindings.add ("webDatabase openDatabase should work", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468691");
    bindings.add ("webDatabase openDatabase's Callback function should be called", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468692");
    bindings.add ("webDatabase openDatabase with empty name should work", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468694");
    bindings.add ("webDatabase Database version should work", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468695");
    bindings.add ("webDatabase Change Database version should be defined", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468696");
    bindings.add ("webDatabase Database version should be changed", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468697");
    bindings.add ("webDatabase Table should be created", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468698");
    bindings.add ("webDatabase Database transaction should be recognized as defined", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468699");
    bindings.add ("webDatabase Database transaction success callback should run", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468700");
    bindings.add ("webDatabase Database transaction error callback should run", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468701");
    bindings.add ("webDatabase Database no parameter transaction should throw error", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468702");
    bindings.add ("webDatabase Database null parameter transaction should throw error", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468703");
    bindings.add ("webDatabase readTransaction should be recognized as defined", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468704");
    bindings.add ("webDatabase readTransaction success callback should run", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468705");
    bindings.add ("webDatabase readTransaction error callback should run", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468706");
    bindings.add ("webDatabase readTransaction no parameter should throw error", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468707");
    bindings.add ("webDatabase readTransaction null parameter should throw error", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468708");
    bindings.add ("webDatabase readTransaction readOnly permission should throw error", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468709");
    bindings.add ("webDatabase executeSQL should be recognized as defined", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468710");
    bindings.add ("webDatabase executeSQL success callback should run", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468711");
    bindings.add ("webDatabase executeSQL error callback should run", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468712");
    bindings.add ("webDatabase executeSQL no parameter should throw error", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468713");
    bindings.add ("webDatabase executeSQL null parameter should throw error", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468714");
    bindings.add ("webDatabase resultSet should have the correct insertID", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468715");
    bindings.add ("webDatabase resultSet should have the correct num of rows", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468716");
    bindings.add ("webDatabase resultSet should have the correct num of rows affected", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468717");
    bindings.add ("webDatabase SQL Error properties should be correct", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468718");
    bindings.add ("webDatabase opening Database with multiple versions should throw error", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468719");
    bindings.add ("webDatabase Database RollBack should work properly", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468720");
    bindings.add ("webDatabase Database largeNumberOfRecords stress test should work", "BlackBerry Developer Tools\\WebWorks API\\HTML5\\HTML5 - " + YUI.framework.bundle_version + "\\HTML5 webDatabase tests", "2468721");
})();
